FROM python

WORKDIR /app

COPY . /app

CMD ["python", "rng.py"]
# this will run the script in the container, but by default docker is only "listening"
# use docker run -i / docker run -it to run interactively

# use docker image inspect IMAGE_HASH to view in more details
