apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: mattdawson2020/kube-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              # ip address, found by inspecting service, it works but this can change
              # value: 10.101.146.64
              value: auth-service.default
              # you can use the service name as this is recognised internally in the cluster as a domain name, similar to docker compose
