apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: mattdawson2020/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              # defining directly
              # value: 'story'
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # initial emptyDir volume type, lets you persist data across container restarts, but only works for one pod
          # multiple pods have their own volumes, so if you are directed to a different pod data is not shared
          # emptyDir: {}

          # creates a volume in a path on 'host', in this case the node running the pods
          # data can persist on pod shutdown and between pods, but not between workers
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate

          # link these pods to the claim for the persistent volume, similar to a join table
          persistentVolumeClaim:
            claimName: host-pvc
