apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  # can be FileSystem or Block
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    # can be mounted as read write by a single node
    - ReadWriteOnce
    # read only but multiple nodes can use it
    # - ReadOnlyMany
    # read write for any number of nodes
    # - ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate
